# Generated by Django 4.0.4 on 2022-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='article', max_length=100, verbose_name='Icon'),
        ),
    ]
