# Generated by Django 4.0.4 on 2022-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('quizroom', '0003_course_enrolled_alter_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='module.module'),
        ),
    ]
