# Generated by Django 4.0.4 on 2022-06-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('quizroom', '0005_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(to='question.question'),
        ),
    ]
