# Generated by Django 4.0.4 on 2022-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('module', '0003_module_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignments',
            field=models.ManyToManyField(to='assignment.assignment'),
        ),
    ]
